### ISSUE TITLE
Add extension to Microsoft Edge Addons

### ISSUE THREAD

**Issue by maxoux53** [gmirmand/ecosia-dark-mode#19]
I propose to add the extension to the Microsoft Edge Addons webstore :
https://developer.microsoft.com/en-us/microsoft-edge/extensions/

**Comment by gmirmand** [comment]
I have already received emails about this, I will try to take the time to do it one day. Thanks

**Comment by maxoux53** [comment]
> I have already received emails about this, I will try to take the time to do it one day. Thanks

Ok, perfect 😉
