### ISSUE TITLE
Bug with homepage

### ISSUE THREAD

**Issue by maxoux53** [gmirmand/ecosia-dark-mode#20]
Bug with homepage :
[Screenshot 1](https://zupimages.net/up/21/01/q6tv.jpeg)
[Screenshot 2](https://zupimages.net/up/21/01/dl82.jpeg)

**Comment by gmirmand** [comment]
Fixed! Thanks a lot for the feedback and for the screenshots, it helps me a lot! (Sorry, it took me a long time to answer, I couldn't be active for a long time)
