### ISSUE TITLE
Colors are not filling correctly

### ISSUE THREAD

**Issue by JayToe** [gmirmand/ecosia-dark-mode#26]
Dark colors aren't filling in correctly, both on desktop and on mobile mode. Pictures are attached.
<img width="868" alt="Bildschirmfoto 2021-02-08 um 10 24 18" src="https://user-images.githubusercontent.com/37263678/107200660-47107980-69f8-11eb-9dbe-e4c67e58e94a.png">
<img width="779" alt="Bildschirmfoto 2021-02-08 um 10 25 47" src="https://user-images.githubusercontent.com/37263678/107200663-4841a680-69f8-11eb-8111-421a00850de1.png">

**Comment by gmirmand** [comment]
These issues have already been identified and will be resolved in the next deployment. The build is still under review so we hope it will be validated soon! Thanks a lot for the feedback! :)

**Comment by JayToe** [comment]
Thanks a lot for your work & effort :)
