### ISSUE TITLE
Edit the bitly link in the description

### ISSUE THREAD

**Issue by maxoux53** [gmirmand/ecosia-dark-mode#27]
You should replace the bitly link that is in the description of **the extension for Microsoft Edge** by this one:

https://bit.ly/3a5EB3L

(Or create one yourself that redirects to https://microsoftedge.microsoft.com/addons/detail/ecosia-the-search-engin/fhfidmlnclkepgapcephbaciajegheco )

**Comment by maxoux53** [comment]
Mais attends...
Tu parles français !
Bon beh ducoup:
Le lien bitly qui est dans la description de l'extension pour Microsoft Edge envoi vers l'extension Ecosia du Chrome Web Store. Alors qu'Ecosia a publié son extension sur le Microsoft Edge Addons. Donc il faudrait remplacer le lien bitly qui envoie vers le CWS par celui là : https://bit.ly/3a5EB3L .

(Forcément, tu n'es pas obligé d'utiliser le lien que j'ai généré, tu peux en créer un toi même tant qu'il redirige vers https://microsoftedge.microsoft.com/addons/detail/ecosia-the-search-engin/fhfidmlnclkepgapcephbaciajegheco )

**Comment by gmirmand** [comment]
Merci !

**Comment by gmirmand** [comment]
Et oui je suis Français ahah ! :D
