### ISSUE TITLE
Ecosia feedback not support by the extension

### ISSUE THREAD

**Issue by maxoux53** [gmirmand/ecosia-dark-mode#28]
Il y a pas longtemps j'ai remarqué que les commentaires Ecosia n'étaient pas prit en charge par l'extension.
Par exemple, quand on cherche une traduction sur Ecosia, un bouton "commentaires" s'affiche et quand on clique dessus ce menu apparait :
![Capture web_3-3-2021_174513_www ecosia org](https://user-images.githubusercontent.com/71935156/109840459-6e99e100-7c48-11eb-8dbb-3d16938f52c2.jpeg)

Ca serait super si le mode sombre les prenaient en charge (les commentaires).

**Comment by gmirmand** [comment]
Bien trouvé, j'appliquerais le correctif au prochain push, merci ! :)
